name: ChargingNetwork
channels:
   - defaults
dependencies:
   # Core requirements
   - python=3.8
   - pip
   - ipython
   - ipykernel
   # Other packages
   - pandas
   - numpy
   - scipy
   - matplotlib
   - tensorflow
   - seaborn
   - pip:
     - overpy
     - lxml