name: ChargingNetwork
channels:
   - defaults
dependencies:
   # Core requirements
   - python=3.8
   - pip
   - ipython
   - ipykernel
   # Other packages
   - pandas
   - numpy
   - scipy
   - astropy
   - matplotlib
   - tensorflow
   - seaborn
   - nodejs
   - pip:
     - overpy
     - lxml
     - wget
     - h5py
     - plotly==5.13.1
     - nbformat
     - kaleido
     - geopy